config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :themes
  resources :images
  resources :values
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match 'index', to: 'main#index', via: :get
  match 'help', to: 'main#help', via: :get
  match 'contacts', to: 'main#contacts', via: :get
  match 'about', to: 'main#about', via: :get

  match 'work', to: 'work#index', via: :get
  match 'choose_image', to: 'work#choose_image', via: :get
  match 'choose_theme', to: 'work#choose_theme', via: :get
  match 'display_theme', to: 'work#display_theme', via: :post

  root 'main#index'

  match 'signup', to: 'users#new', via: :get
  match 'signin', to: 'sessions#new', via: :get
  match 'signout', to: 'sessions#destroy', via: :delete

  namespace :api, defaults: { format: :json } do

    match 'next_image', to: 'api#next_image', via: :get
    match 'prev_image', to: 'api#prev_image', via: 'get'
    match 'save_value', to: 'api#save_value', via: :get
  end

  match 'results_list', to: 'work#results_list', via: :get

  match 'save_value', to: 'api/api#save_value', via: :get
end

app/models/user.rb
class User < ApplicationRecord

  has_many :values, dependent: :destroy

  before_save { self.email = email.downcase }

  before_create :create_remember_token

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def self.all_cached
    Rails.cache.fetch('User.all') { all }
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all_cached
  end

  def show
    user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        sign_in @user
        # flash.now[:notice] = "Welcome to the Experteese - sample App!"
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        # flash.now[:alert] = "Bad registration"
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation.x-form__errors
      %h3.like-h3= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul.x-form__errors-list
        - @user.errors.full_messages.each do |msg|
          %li.x-form__error= msg

  .x-form__fields
    .x-form__item
      = f.label t('.name'), class: 'x-form__label'
      = f.text_field :name, class: 'x-form__field'
    .x-form__item
      = f.label t('.email'), class: 'x-form__label'
      = f.text_field :email, class: 'x-form__field'
    .x-form__item
      = f.label t('.password'), class: 'x-form__label'
      = f.password_field :password, class: 'x-form__field'
    .x-form__item
      = f.label t('.password_confirmation'), class: 'x-form__label'
      = f.password_field :password_confirmation, class: 'x-form__field'
    .x-form__actions
      = f.submit t('.create_account'), class: 'x-button'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Email
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
- provide(:title, "Sign up")

%h1.like-h1= t('.sign_up')

= render 'form'

app/views/users/show.html.haml
.x-dashboard
  .x-dashboard__avatar
    = gravatar_for @user
  %ul.x-dashboard__info
    %li.x-dashboard__info-item
      = t('.name')
      =':'
      = @user.name

    %li.x-dashboard__info-item
      = t('.email')
      =':'
      = @user.email

= link_to t('.start'), work_path, class: "x-button"