config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :themes
  resources :images
  resources :values
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match 'index', to: 'main#index', via: :get
  match 'help', to: 'main#help', via: :get
  match 'contacts', to: 'main#contacts', via: :get
  match 'about', to: 'main#about', via: :get

  match 'work', to: 'work#index', via: :get
  match 'choose_image', to: 'work#choose_image', via: :get
  match 'choose_theme', to: 'work#choose_theme', via: :get
  match 'display_theme', to: 'work#display_theme', via: :post

  root 'main#index'

  match 'signup', to: 'users#new', via: :get
  match 'signin', to: 'sessions#new', via: :get
  match 'signout', to: 'sessions#destroy', via: :delete

  namespace :api, defaults: { format: :json } do

    match 'next_image', to: 'api#next_image', via: :get
    match 'prev_image', to: 'api#prev_image', via: 'get'
    match 'save_value', to: 'api#save_value', via: :get
  end

  match 'results_list', to: 'work#results_list', via: :get

  match 'save_value', to: 'api/api#save_value', via: :get
end

app/views/shared/_footer.html.haml
%footer
  .x-container.x-footer
    .x-footer__inner
      %div.x-footer__copyrught Expertise &#169; 2017
      %nav.x-footer__nav
        = link_to t('.home'), root_path, class: ['x-footer__nav-item', current_page?(root_path) ? 'is-active' : '']
        = link_to t('.about'), about_path, class: ['x-footer__nav-item', current_page?(about_path) ? 'is-active' : '']
        = link_to t('.help'), help_path, class: ['x-footer__nav-item', current_page?(help_path) ? 'is-active' : '']
        = link_to t('.contacts'), contacts_path, class: ['x-footer__nav-item', current_page?(contacts_path) ? 'is-active' : '']

app/views/shared/_header.html.haml
%header
  .x-container.x-header
    .x-header__inner
      %nav.x-header__nav
        = link_to t('.home'), root_path, class: ['x-header__nav-item', current_page?(root_path) ? 'is-active' : '']
        = link_to t('.about'), about_path, class: ['x-header__nav-item', current_page?(about_path) ? 'is-active' : '']
        = link_to t('.help'), help_path, class: ['x-header__nav-item', current_page?(help_path) ? 'is-active' : '']
        = link_to t('.contacts'), contacts_path, class: ['x-header__nav-item', current_page?(contacts_path) ? 'is-active' : '']
      %nav.x-header__nav.x-header__nav--right
        .x-header__lang
          - if locale == :ru
            %span.x-header__lang-item ru
            = link_to 'en', { locale: :en }, { class: 'x-header__lang-item is-disabled' }
          - else
            = link_to 'ru', { locale: :ru }, { class: 'x-header__lang-item is-disabled' }
            %span.x-header__lang-item en
        - if signed_in?
          .x-header__user
            .x-header__avatar
              = gravatar_for current_user
            .x-header__mail.js-toggle #{current_user.email}
            .x-header__dropdown
              = link_to t('.profile'), current_user, class: 'x-header__dropdown-item'
              = link_to t('.sign_out'), signout_path, method: "delete", class: 'x-header__dropdown-item'
        - else
          = link_to t('.sign_in'), signin_path, class: 'x-header__nav-item'
    .x-header__center
      .x-header__core
        .x-header__label exp